Repository OntimizeWeb/ontimize-web-ngx-quickstart, pull requests merged in 2022-12, with the labels that each got.

#146 updated the asset configuration with the map assets in angular.json
  angular.json
Labels: bug

#148 Sync development preview to 8.x.x
  angular.json
  package-lock.json
  package.json
  src/app/app.config.ts
  src/app/main/accounts/detail/accounts-detail.component.html
  src/app/main/accounts/detail/accounts-detail.component.scss
  src/assets/themes/o-madder-lake-jet-dark.css
  src/assets/themes/o-madder-lake-jet.css
  src/assets/themes/o-oxford-blue-emerald-dark.css
  src/assets/themes/o-oxford-blue-emerald.css
  src/assets/themes/o-prussian-celtic-blue-dark.css
  src/assets/themes/o-prussian-celtic-blue.css
  src/assets/themes/o-violet-blues-dark.css
  src/assets/themes/o-violet-blues.css
  src/assets/themes/ontimize-dark.css
  src/assets/themes/ontimize.css
Labels: enhancement

#149 Sync 8.x.x to master
  .github/workflows/build-release.yml
  angular.json
  package-lock.json
  package.json
  src/app/app.config.ts
  src/app/main/accounts/detail/accounts-detail.component.html
  src/app/main/accounts/detail/accounts-detail.component.scss
  src/app/main/employees/employees-home/employees-home.component.html
  src/assets/themes/o-madder-lake-jet-dark.css
  src/assets/themes/o-madder-lake-jet.css
  src/assets/themes/o-oxford-blue-emerald-dark.css
  src/assets/themes/o-oxford-blue-emerald.css
  src/assets/themes/o-prussian-celtic-blue-dark.css
  src/assets/themes/o-prussian-celtic-blue.css
  src/assets/themes/o-violet-blues-dark.css
  src/assets/themes/o-violet-blues.css
  src/assets/themes/ontimize-dark.css
  src/assets/themes/ontimize.css
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: release

#159 Release 8.2.0
  package.json
Labels: release
